name: Static Tests

on: [pull_request]

jobs:
  static-tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Unit Test
        run: yarn test

      - name: ES Lint
        run: yarn lint

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v1
        with:
          configFile: 'commitlint.config.js'

  commitlint:
    name: Commit Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v3
        with:
          configFile: 'commitlint.config.js'
